In [2]:
import numpy as np


In [3]:
My_array=np.array([[1,2,3,4],[6,7,8,9]])
print(My_array)

[[1 2 3 4]
 [6 7 8 9]]


In [4]:
print(My_array.shape)

(2, 4)


In [8]:
My_array=np.zeros(2)
print(My_array)

[0. 0.]


In [5]:
My_array=np.ones(50)
print(My_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1.]


In [6]:
My_array=np.empty(3)
print(My_array)

[6.90651007e-310 1.91710119e-316 6.90647962e-310]


In [7]:
range23=np.arange(0,10)
print(range23)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
value=np.linspace(2,5,3)
print(value)

[2.  3.5 5. ]


In [9]:
#random integers in 2d array
value=np.random.randint(2,6,(2,3,2))
print(value)

[[[2 2]
  [4 2]
  [5 4]]

 [[4 3]
  [4 4]
  [3 5]]]


In [10]:
print(value*2)


[[[ 4  4]
  [ 8  4]
  [10  8]]

 [[ 8  6]
  [ 8  8]
  [ 6 10]]]


In [11]:
print(value+value)

[[[ 4  4]
  [ 8  4]
  [10  8]]

 [[ 8  6]
  [ 8  8]
  [ 6 10]]]


In [12]:
cutu= np.arange(2,20,3)
print(cutu)
cutu=np.once(10)
print(cutu)

[ 2  5  8 11 14 17]


AttributeError: module 'numpy' has no attribute 'once'

In [ ]:
motu= np.linspace(2,5,5)
#Calculating step size = (5 - 2) / (4 - 1) = 4 / 3 = 1.33333333
#next value=previous + step_size
print(motu)

import numpy as np

motu = np.linspace(2, 5, 5)
# start = 2
# stop = 5
# num = 5 (number of samples)
# step size = (stop - start) / (num - 1)
# step size = (5 - 2) / (5 - 1)
# step size = 3 / 4
# step size = 0.75

[2.   2.75 3.5  4.25 5.  ]


In [119]:
#np. always create an array
fruitu= np.random.rand(2,3)
#It generate 2d array of 2 rows and 3 columns
print(fruitu)

[[0.26602055 0.9497268  0.88472069]
 [0.75538161 0.95749555 0.06175533]]


In [120]:
print(fruitu*10)

[[2.66020554 9.49726796 8.84720689]
 [7.55381606 9.57495545 0.61755329]]


In [121]:
print(fruitu+fruitu)
array=np.array([[1,2,3],[4,5,6]])
print(array+array)


[[0.53204111 1.89945359 1.76944138]
 [1.51076321 1.91499109 0.12351066]]
[[ 2  4  6]
 [ 8 10 12]]


In [122]:
print(array*2)
print(np.add(array,array))

[[ 2  4  6]
 [ 8 10 12]]
[[ 2  4  6]
 [ 8 10 12]]


In [123]:
print(array+6)

[[ 7  8  9]
 [10 11 12]]


In [124]:
print(np.sqrt(array**2))

[[1. 2. 3.]
 [4. 5. 6.]]


In [125]:
#In numpy we provide the degree in radian not in degree
degree=90
radian2=(np.deg2rad(degree))

print(np.sin(radian2))
print(int(np.cos(radian2)))
print(np.tan(radian2))


1.0
0
1.633123935319537e+16


In [126]:
degree = 90
radian2 = np.radians(degree)
print(np.sin(radian2))
print(np.cos(radian2))
print(np.tan(radian2))

1.0
6.123233995736766e-17
1.633123935319537e+16


In [127]:
#1D array
array1=np.array([[['asd',"asdf","asd"],[1,2,3],[4,5,6]],
                 [[5,4,3],[123,4,5],[1,2,3]]
                 ])
print(array1)
print(array1.shape)#Number of element in each dimention
print(array1.dtype)

[[['asd' 'asdf' 'asd']
  ['1' '2' '3']
  ['4' '5' '6']]

 [['5' '4' '3']
  ['123' '4' '5']
  ['1' '2' '3']]]
(2, 3, 3)
<U21


In [18]:
array1=np.array(['asd',"asdzxcasdfhasjkfaslkfj","aszxc",'qwe'])
print(array1)
print(array1.shape)#Number of element in each dimention
print(array1.dtype)

['asd' 'asdzxcasdfhasjkfaslkfj' 'aszxc' 'qwe']
(4,)
<U22


In [19]:
array2d=np.array([[1.2,2.3,3.4],[2.3,5.5,6.2]])
print(array2d)

#In 2D array shape tells us the row and column of matrix
print(array2d.shape) 
print(array2d.dtype)

[[1.2 2.3 3.4]
 [2.3 5.5 6.2]]
(2, 3)
float64


In [20]:
array3d=np.array([
    [[1.5,2.2,3.5], [4.5,5.2,6.5]],
    [[7.5,8.2,9.5],  [10,11,12]]
])
print(array3d)


[[[ 1.5  2.2  3.5]
  [ 4.5  5.2  6.5]]

 [[ 7.5  8.2  9.5]
  [10.  11.  12. ]]]


In [21]:

array_float=np.array([1.0,2.3,4.2])
print(array_float)
print(array_float.shape)
print(array2d.shape)
print(array3d.shape)
print(array_float.dtype)

print(array2d.dtype)
print(array3d.dtype)

[1.  2.3 4.2]
(3,)
(2, 3)
(2, 2, 3)
float64
float64
float64


In [22]:
#Dtype of empty is float
empty_array=np.empty(5)
print(empty_array)
print(empty_array.shape)
print(empty_array.dtype)

print(array3d.size)



[2.   2.75 3.5  4.25 5.  ]
(5,)
float64
12


In [23]:
array3d=np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9], [10,11,12]]
])

#Blue breakets are x 
#yellow are Y
#and inner values are z

array=np.array([1,2,3])
print(array.ndim)
print(array2d.ndim)
print(array3d.ndim)
print(array3d.shape)


1
2
3
(2, 2, 3)


In [24]:
print(array3d.nbytes)
print(array2d.nbytes)
print(array.nbytes)



96
48
24


In [25]:
#Accessing the values from 3d dimensions
print(array3d)
print(array3d[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [83]:
print(np.identity(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [29]:
#Determinanat 
amatrix=np.array(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]],
        
        ])
# print(amatrix.size())

#print(int(np.linalg.det(amatrix)))
print(np.trace(amatrix))
# Create a 3D matrix
matrix_3d = np.array([[[1, 2, 3], [4, 5, 6],[7, 8, 9]],
                      [[10, 11, 12], [13, 14, 15],[16, 17, 18]]])
print(np.trace(matrix_3d))
#Eigenvalues 
#https://math.libretexts.org/Bookshelves/Linear_Algebra/A_First_Course_in_Linear_Algebra_(Kuttler)/07%3A_Spectral_Theory/7.01%3A_Eigenvalues_and_Eigenvectors_of_a_Matrix
#this matrix is such that  AX results in  kX  , for every vector  X.
print(np.linalg.eigvals(amatrix))


[ 8 10]
[14 16 18]
[[-0.37228132  5.37228132]
 [-0.15206735 13.15206735]]


In [94]:
#inverse of a metrix
print(np.linalg.inv(amatrix))

[[[-2.   1. ]
  [ 1.5 -0.5]]

 [[-4.   3. ]
  [ 3.5 -2.5]]]


In [104]:
#Sum along axis
#0 axis: parallel values in each row
#1 axis: Parallel values of rows inside each row.
#2 axis: Sum of values of inside rows.
#Sum along axis
print(amatrix)
sum_axis_0=np.sum(amatrix,axis=0)
print("SUm aling axis 0(columns):",sum_axis_0)
sum_axis_1=np.sum(amatrix,axis=1)
print("SUm aling axis 1(columns):",sum_axis_1)
sum_axis_2=np.sum(amatrix,axis=2)
print("SUm aling axis 2(columns):",sum_axis_2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
SUm aling axis 0(columns): [[ 6  8]
 [10 12]]
SUm aling axis 1(columns): [[ 4  6]
 [12 14]]
SUm aling axis 2(columns): [[ 3  7]
 [11 15]]


In [103]:
print(amatrix.shape)

(2, 2, 2)


In [92]:
tensor= np.array([
    [[1,2,3,4],[5,6,7,8],[9,10,11,12]],
    [[13,14,15,16],[17,18,19,20],[21,22,23,24]]
    ]
)
print(tensor.shape)


(2, 3, 4)


In [94]:
sum0=np.sum(tensor,axis=0)
print(sum0)
sum1=np.sum(tensor,axis=1)
print(sum1)
sum2=np.sum(tensor,axis=2)
print(sum2)


[[14 16 18 20]
 [22 24 26 28]
 [30 32 34 36]]
[[15 18 21 24]
 [51 54 57 60]]
[[10 26 42]
 [58 74 90]]


In [98]:
my_array = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16])
#For reshaping the values passed to reshape when both multiplied should give us size of array
reshaped_array= my_array.reshape(16,1)
print(reshaped_array)


[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [103]:
reshaped_array= my_array.reshape(16,1)
print(reshaped_array)

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [15]
 [16]]


In [30]:
array2d=np.ones(10)
print(array2d)
array2d=np.zeros(11)
print(array2d)
array2d=np.empty(10)
print(array2d)



[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [14]:
a=12345
print(int(a%10))
b=a/10
int(b)

5


1234

In [17]:
#Linear Algebra
#inner product of arrays
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(np.inner(a, b))  # Output: 32


print(np.linalg.outer(a,b))


32


AttributeError: module 'numpy.linalg' has no attribute 'outer'

In [ ]:
output=lambda x 